import type { ConfigKey, CurrentConfig, Settings } from "@/shared/types";
import { BinaryFlag, BypassMode } from "./enums";

export const CONFIG_KEYS: readonly ConfigKey[] = [
  "power_stop",
  "power_start",
  "power_stop_time",
  "charge_full",
  "charge_full_mode",
  "charge_full_wait_sec",
  "power_reset",
  "unplug_restore",
  "compatibility_mode",
  "stop_hold_wakelock",
  "notify_charge_event",
  "notify_charge_kinds",
  "notify_power_status",
  "temperature_switch",
  "temperature_switch_stop",
  "temperature_switch_start",
  "loop_interval_sec",
  "loop_interval_maintain_sec",
  "switch_verify_sec",
  "switch_batch_blind",
  "wireless_policy",
  "app_stop",
  "app_stop_list",
  "history_enable",
  "history_interval_sec",
  "power_saver",
  "loop_interval_idle_sec",
  "loop_interval_idle_native_sec",
  "loop_interval_plugged_sec",
  "loop_interval_plugged_native_sec",
  "loop_interval_near_window",
  "native_daemon",
  "native_impl",
  "chart_show",
] as const;

export const DEFAULTS: Settings = {
  power_stop: "100",
  power_start: "95",
  power_stop_time: "3",
  charge_full: BinaryFlag.Off,
  charge_full_mode: "auto",
  charge_full_wait_sec: "600",
  power_reset: BinaryFlag.Off,
  unplug_restore: BinaryFlag.On,
  compatibility_mode: BinaryFlag.Off,
  stop_hold_wakelock: "auto",
  notify_charge_event: BinaryFlag.Off,
  notify_charge_kinds: "stop,resume,fail",
  notify_power_status: BinaryFlag.Off,
  temperature_switch: BinaryFlag.On,
  temperature_switch_stop: "60",
  temperature_switch_start: "50",
  loop_interval_sec: "3",
  loop_interval_maintain_sec: "8",
  switch_verify_sec: "1",
  switch_batch_blind: BinaryFlag.On,
  wireless_policy: "same",
  app_stop: BinaryFlag.Off,
  app_stop_list: "",
  history_enable: BinaryFlag.On,
  history_interval_sec: "60",
  power_saver: BinaryFlag.On,
  loop_interval_idle_sec: "90",
  loop_interval_idle_native_sec: "600",
  loop_interval_plugged_sec: "15",
  loop_interval_plugged_native_sec: "90",
  loop_interval_near_window: "3",
  native_daemon: BinaryFlag.On,
  native_impl: "rust",
  chart_show: BinaryFlag.On,
};

export const CURRENT_DEFAULTS: CurrentConfig = {
  current_control: 0,
  bypass_enable: 0,
  battery_stop: 110,
  bypass_temp: 110,
  bypass_schedule: [],
  slow_charge: 110,
  default_current_max: 5000000,
  temperature_current: 0,
  default_current_limit: 40,
  default_current_max_limit: 1500000,
  temperature_current_limit: 45,
  constant_current_max: 100000,
  app_limit: 0,
  app_current_max: 200000,
  app_list: [
    "com.tencent.tmgp.sgame",
    "com.tencent.tmgp.pubgmhd",
    "com.miHoYo.Yuanshen",
    "com.tencent.lolm",
  ],
  bypass_mode: BypassMode.Sim,
  safety_temp_max: 48,
  battery_current: [
    "/sys/class/power_supply/battery/fast_charge_current",
    "/sys/class/power_supply/battery/current_max",
    "/sys/class/power_supply/battery/constant_charge_current",
    "/sys/class/power_supply/battery/constant_charge_current_max",
    "/sys/class/power_supply/main/constant_charge_current_max",
  ],
  restricted: [
    "/sys/class/qcom-battery/restrict_chg value=1",
    "/sys/class/qcom-battery/restricted_charging value=1",
    "/sys/class/power_supply/battery/step_charging_enabled value=0",
  ],
  current_reaffirm_sec: 24,
  current_drift_ua: 300000,
  current_step_ua: 0,
};
